
tags: [ "" "" ""]

variables:
  MVN_VERSION: 3.9.6
  TERRAFORM_VERSION: 1.13.3
  TERRAGRUNT_VERSION: 0.87.0
  GRADLE_VERSION: 8.4
  GO_VERSION: 1.22.2
  IMAGE_NAME: "glrunner"
  DOCKER_DRIVER: overlay2
  DOCKER_PASSWORD: ""
  DOCKER_USER: ""
  DOCKER_REGISTRY: "docker.io/ss0x44"
  DOCKER_REGISTRY_IMAGE: "$DOCKER_REGISTRY/$IMAGE"
  VERSION:
    description: "select version : '0.0.1'"
    default: '0.0.1'
    options:
      - '0.0.1'
stages:
  - build  
build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - MAJOR=$(echo $VERSION | cut -d. -f1)
    - MINOR=$(echo $VERSION | cut -d. -f2)
    - PATCH=$(echo $VERSION | cut -d. -f3)
    - PATCH=$((PATCH + 1))
    - if [ "$PATCH" -gt 9 ]; then PATCH=0; MINOR=$((MINOR + 1)); fi
    - if [ "$MINOR" -gt 9 ]; then MINOR=0; MAJOR=$((MAJOR + 1)); fi
    - LATEST="v$MAJOR.$MINOR.$PATCH"
    - docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD" "$DOCKER_REGISTRY"
    - docker build -t "DOCKER_REGISTRY_IMAGE:$LATEST" .
    - docker tag "$IMAGE_NAME" "$DOCKER_REGISTRY_IMAGE:$LATEST"

    - docker push "$DOCKER_REGISTRY_IMAGE:$LATEST"
